apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: w9-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/<your-repo>.git
    targetRevision: main
    path: Cloud-DevOps/W9/day-a/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
